dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: BTqfJt/YRY7mVgRR45jMEeVhI5GjGwKc+uiKkBl9afkQmthEyjEWxbiwtt3aGB+Fl3neIjpqrl0FDcBUBVSFAzDOzK5SQl17YndzzndJx16F8Dm9KxsIBjyTMpiRXcKQZ3kCdLYb88v5557sPNkWOTpmqSfX16gZG+8y1iQUnLxxRpLaQkt4ONNnLgnxeiinWvOsc/IowoE+aVqUOOs6Slq5zaHuyQIUxApfaeXXY3ZvlyTFxdKdPeVUJCUomiCYkeZ7fr6GHvSeks7C1o1IrA/PtTN6MsTb4msHv8lC4NVj4PtuI5uKVeVKo6RFdgREg/U80WV6XIeTGc91pew2GEJjtwQddVKu6x+M7suE5AAwg7B42O5D2QMlHpjakltFp5cqN5SdjqNOsFALuh0aRX5zEgDIZmQ/voOEL2FyGDMAn0u8J1c8IIpaZ6uL+57gwIQt8zNOIkH1QniMMkAlRG1Wo2v+DZe2nHvUNywLdVWB1uAZUHyKt1R0V7tHWY3RJbYxZ7YeqCrhE/94qz33KU+ahmZRLPLN9m5XO3uk7imiDiGrEL1Txv4EYr1D7E5IP4viP7tmYv7G0fQMdgp1MQD9Y6eaYKNrLX1/kBJN5Y3qSxLw6dgoHrabCS8nhqKMTrjr4UeyLFfHpkHnRlU3YRPs4RlJK/DfCGfHbyCmbTU=
  file: Gerbers/MNT-104_gerbers.zip
  on:
    repo: w4xzr/MNT-104
  skip_cleanup: 'true'
